language: r
sudo: required
dist: trusty
bioc_required: true
cache:
  timeout: 2000
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/R/Library
warnings_are_errors: true
python:
  - "3.6"
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
before_install:
 - source <( curl --insecure https://raw.githubusercontent.com/dynverse/dynmethods/master/.travis_install_python.sh ) # use travis's own python
install:
  - pip3 install --user --upgrade --only-binary=numpy,scipy numpy scipy
  - pip3 install --user --upgrade matplotlib tqdm GPy
  - R -e 'install.packages("devtools")'
  - R -e 'setRepositories(ind = 1:2)'
  - R -e 'devtools::install(dependencies = T, upgrade = T)'
