language: r
sudo: required
dist: trusty
bioc_required: true
cache: packages
warnings_are_errors: true
addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools
      - python3-wheel
install:
 - "pip3 install --upgrade "numpy pandas matplotlib tqdm GPy"
