language: r
sudo: required
dist: trusty
bioc_required: true
cache: packages
warnings_are_errors: true
python:
  - "3.6"
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
before_install:
  - sudo apt-get -y install python3-pip
  - sudo pip3 install --upgrade pip setuptools wheel
  - python3 -V
  - pip3 -V
install:
  - sudo pip3 install --upgrade --only-binary=numpy,scipy numpy scipy
  - sudo pip3 install --upgrade pandas matplotlib tqdm GPy
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_github("r-lib/callr")'
  - R -e 'devtools::install_github("dynalysis/devtools")'
  - R -e 'devtools::install(dependencies = TRUE, upgrade_dependencies = TRUE)'
